### ISSUE TITLE
Help with automation: understanding how schema's and presets work

### ISSUE THREAD

**Issue by unreal4u** [plugwise/plugwise-beta#156]
Hi! 

First of all: excellent work guys! I bought Smile+Anna recently and your integration works as a charm! Kudos to you!!

That being said, I need some help with setting up an automation. I have 2 automations at home, one for when I leave and the other for when I arrive.

When I go out, I tell it to set the 'away' preset_mode: 

```
- id: '1612911872117'
  alias: Set climate "away" when people are not present
  description: ''
  trigger:
  - platform: mqtt
    topic: sensors/whoishome/peoplepresent
    payload: 'no'
  condition: []
  action:
  - service: climate.set_preset_mode
    data:
      preset_mode: away
      entity_id: climate.anna
  mode: single
```

However, if I understand it correctly, the schema will still run in the background right? Say I have a schema that looks like follows:

22:00 - asleep
09:00 - home

What if I leave the house at 08:00 and don't come back until 17:00? If I send the above command at 08:00, will Smile still activate the 'home' protocol at 09:00?

And if sending the command above disables the schema: is there a way to tell Smile to enable it back as soon as I come home? Like, if I come home at 23:00 I don't want to enable the 'home' preset, but let Smile decide what to do based on my schema.

The more I think about it, the more I am inclined to implement this directly in either Home Assistant or NodeRed. However, I would like to fallback to the schema just in case Home Assistant crashes and stops sending commands or whatnot. It would also make a vacation schema more difficult to implement.

Sorry if this doesn't belong here, in that case just tell me and I'll post it where it should!

Greetings.

**Comment by CoMPaTech** [comment]
Hi Camilo, just spotted this issue in our former repo, just moving it here to ensure we catch up with it.

If I read you right, indeed while the schema is still active it probably will override (I personally don't use away so I'd have to test it) - the way I guess it would work is either it overrides your away (preferring the schema) so it is at least 'warm' when you get back home.

You could indeed just switch from HA or NR, but keep in mind that these thermostats include 'smartness' (even the old digital things were 'smart' in that way) to 'know' how much time it takes to heat up your home - HA wouldn't know that. (That's why they where formerly known as 'learning thermostats', they know how long it takes to heat up the home - the 'smart' versions we have today also take external temperature into account to be even 'better' at predicting).

**Comment by bouwew** [comment]
@unreal4u I can confirm: the schedule always stays active in the background and will take over at the next schedule = temperature change. So, to make it work as you want it, you need to do the following:
- when going away: first disable the schedule (via a, wait a few seconds, then set the preset
- when returning: enable the schedule

Here's an example of my going away automation:
```
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.anna
      hvac_mode: heat
  - delay: 00:00:03
  - service: climate.set_preset_mode
    data:
      entity_id: climate.anna
      preset_mode: home
  - delay: 00:00:03
  - service: climate.set_preset_mode
    data:
      entity_id: climate.anna
      preset_mode: away
```
I'm changing the preset first to another one then to the final one because at the time I made this it wouldn't work otherwise. You can try and see if it works with setting the preset in one go.

And this is my coming home automation:
```
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.anna
      hvac_mode: auto
```
